### ISSUE TITLE
Fix Codecov

### ISSUE THREAD

**Issue by uo264074** [Arquisoft/viade_en1a#101]
We are not being shown the real amount of code coverage of our app.
The Codecov reports return an error and we must solve that.

**Comment by AdrianPerezManso** [comment]
Just fixed this problem. When using the [generator](https://github.com/inrupt/generator-solid-react), the scripts.test field in package.json is modified to `"node scripts/test.js"`, so we have to add `--coverage` again in order to let the tests be seen by Codecov
