### ISSUE TITLE
Fix app deployed in GH Pages

### ISSUE THREAD

**Issue by uo264074** [Arquisoft/viade_en1a#38]
Links and images, as well as internationalized texts are not working

**Comment by AdrianPerezManso** [comment]
We tried to set a baseRoute in the BrowserRouter, so the application deploys in [https://arquisoft.github.io/viade_en1a/](url). However, some of the resources are not looked up in this URL, but in [https://arquisoft.github.io/](url), and thus, they are not found.

**Comment by uo264074** [comment]
We found how to show images properly, but we are not able to load internationalized mesages yet.
To show images:
    - They need to be inside the src folder (they are already, in /assets)
    - Import them as a JS object e.g., import nav_logo from './../../assets/img/my_nav_logo.png';
    - Use them like this: <img src= {nav_logo} alt="inrupt" />
