### ISSUE TITLE
Link to create tests for the application

### ISSUE THREAD

**Issue by AdrianPerezManso** [Arquisoft/viade_en1a#59]
[This link](https://create-react-app.dev/docs/running-tests/) may be helpful to see some fundamentals about React testing.

**Comment by NutBandera** [comment]
Cucumber tutorial: https://cucumber.io/docs/guides/10-minute-tutorial/

**Comment by AdrianPerezManso** [comment]
In order to know how to manage Solid PODs, I've created a topic [here ](https://forum.solidproject.org/t/solid-session-testing/2858/)so we have a better knowledge about unit-testing Solid applications.
