### ISSUE TITLE
Share routes with a friend

### ISSUE THREAD

**Issue by AdrianPerezManso** [Arquisoft/viade_en1a#73]

**Comment by AdrianPerezManso** [comment]
We tried the following approach in order to share routes:
* User A clicks "Share route" and chooses the friend to whom is sent
* The system tries to create the folder "routes" and copies the route file inside
* User B can access the file and see its contents

However, this approach has some **issues**, f.i **we don't have permissions to write into the folder**, and we need to be Owner of that specific folder. Another problem is that **we cannot create the folder if it does not exist**, because it won't take the right permissions commented before. 

For these reasons, we have decided to **change the behaviour of sharing routes**, and the steps will be the following:
* User A clicks "Share route" and chooses the friend to whom is sent
* A URL is generated, providing the location of the file to be shared. An example of this system is sharing a resource in Google Drive
* Then, the generated URL has to be delivered externally to the application to User B
* User B signs in the system and clicks the link, that will automatically create into his POD a folder "routes/<nameOfUserA>" and the file with the route.

With this strategy, we **avoid the write-permission problem** we had before.

Due to the change, we delay the completion of this functionality that will be fulfilled as soon as possible.

**Comment by AdrianPerezManso** [comment]
We are discussing some stuff regarding this feature [here](https://gitter.im/solid/chat), given the issues shown in the comment before

**Comment by uo264074** [comment]
Aswell as [here](https://forum.solidproject.org/t/we-are-not-sure-how-we-could-share-files-between-users/2780/2)

**Comment by AdrianPerezManso** [comment]
OK, the evolution of this discussion has grown in the [link ](https://forum.solidproject.org/t/we-are-not-sure-how-we-could-share-files-between-users/2780)provided by Victor in the comment before, and we have finally arrived to a conclussion about how the share routes system works:

* User A clicks "Share route" and chooses the friend to whom is sent
* A message is sent to the "**inbox**" folder of User B with .ttl format
* This message contains the URL for accessing the file in User A's POD, which User B can read

We had to change some things from the original POD management:

* Now the routes, when they are uploaded, are placed in the folder "**public/routes/**" instead of the former folder "**routes/**"
* Given the previous point, now the routes are fetched from the "**public/routes/**" folder

In theory, the next constraints are not something to be changed, because it is the setting by default, but in case this is not the case, you have to fulfill the next requirements:

* Put **Everyone** as **Submitter** in folder "**inbox**"
* Put **Everyone** as **Viewer** in "**public/**"
* Put the file you want to share in "**public/**" folder or any subdirectory

**Comment by AdrianPerezManso** [comment]
I've just pushed the i18 version together with a basic error handling code

**Comment by AdrianPerezManso** [comment]
We can conclude this issue as far as its funcionality is concerned. The part where User B receives the mail and how it is managed will be discussed in #95

**Comment by AdrianPerezManso** [comment]
Due to some issues regarding privacy, we are reopening this issue
