### ISSUE TITLE
Fix issue with friend's pic if they do not have one

### ISSUE THREAD

**Issue by uo264074** [Arquisoft/viade_en1a#78]
If a friend does not have a profile pic, a "not loaded image" icon is shown in the friends tab.
Probably we should not show anything.

**Comment by AdrianPerezManso** [comment]
This is the new view of the Friends page:

![image](https://user-images.githubusercontent.com/56108486/77832973-2c177c80-713a-11ea-9f56-46086d3d36f1.png)
